/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 5c4e2a091282410057ff3fa5b025cbcd)
interface __BaseEnv_Env {
	SOURCE: R2Bucket;
	ARCHIVES: R2Bucket;
	PHOTO_BACKUP_QUEUE: Queue;
	BACKEND_BASE_URL: "https://bioskintech.vercel.app";
	MAX_DELIVERY_ATTEMPTS: "4";
	ANNUAL_BACKUP_SERVICE_SECRET: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "BACKEND_BASE_URL" | "MAX_DELIVERY_ATTEMPTS" | "ANNUAL_BACKUP_SERVICE_SECRET">> {}
}
